// <auto-generated />
namespace MarketplaceMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Cascade2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cascade2));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181515564_Cascade2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
